In [9]:
import numpy as np
import cv2

In [10]:
img = cv2.imread("smallgray.png", 0)

In [11]:
print (img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [12]:
print (img[0:2])

[[187 158 104 121 143]
 [198 125 255 255 147]]


In [13]:
print (img[0:2, 2:4])

[[104 121]
 [255 255]]


In [14]:
print (img[2, 4])

182


In [15]:
print (img[1, 2])

255


In [16]:
for i in img.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [17]:
for i in img.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
